/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Batches */
        get: operations["list_batches_api_batches_get"];
        put?: never;
        /** Create Batch */
        post: operations["create_batch_api_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Batch */
        post: operations["approve_batch_api_batches__id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Batch */
        post: operations["reject_batch_api_batches__id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Batch */
        get: operations["export_batch_api_batches__id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{id}/redeliver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeliver Batch */
        post: operations["redeliver_batch_api_batches__id__redeliver_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaign/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Campaign Receipt */
        post: operations["campaign_receipt_api_campaign_receipts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallets/locked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locked Wallets */
        get: operations["list_locked_wallets_api_wallets_locked_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch Audit */
        get: operations["get_batch_audit_api_batches__id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Score */
        post: operations["score_api_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEntry */
        AuditEntry: {
            /** Id */
            id: string;
            /** Actor Id */
            actor_id?: string | null;
            actor_role: components["schemas"]["AuditRole"];
            /** Action */
            action: string;
            /** Target Id */
            target_id: string;
            /** Metadata */
            metadata?: {
                [key: string]: string | number | boolean | string[] | null;
            };
            /** Created At */
            created_at: string;
        };
        /**
         * AuditRole
         * @enum {string}
         */
        AuditRole: "analyst" | "approver" | "system";
        /** Batch */
        Batch: {
            /** Id */
            id: string;
            cause: components["schemas"]["CauseFamily"];
            /** Remedy Code */
            remedy_code: string;
            /** Unit Cost Bdt */
            unit_cost_bdt: number;
            /** Wallet Count */
            wallet_count: number;
            status: components["schemas"]["BatchStatus"];
            /** Proposed By */
            proposed_by: string;
            /** Decided By */
            decided_by?: string | null;
            /** Decided At */
            decided_at?: string | null;
            /** Decision Note */
            decision_note?: string | null;
            /** Created At */
            created_at: string;
            sms?: components["schemas"]["SmsStatus"] | null;
        };
        /**
         * BatchStatus
         * @enum {string}
         */
        BatchStatus: "proposed" | "approved" | "rejected";
        /**
         * CauseFamily
         * @enum {string}
         */
        CauseFamily: "job_exit" | "migration" | "solved_problem" | "fee_shock" | "supply_failure";
        /** Contribution */
        Contribution: {
            /** Feature */
            feature: string;
            /** Value */
            value: number;
            /** Contribution */
            contribution: number;
        };
        /** CreateBatchRequest */
        CreateBatchRequest: {
            cause: components["schemas"]["CauseFamily"];
            /** Wallet Ids */
            wallet_ids: string[];
        };
        /** DecisionRequest */
        DecisionRequest: {
            /** Note */
            note: string;
        };
        /** DeliveryResult */
        DeliveryResult: {
            /** Delivered */
            delivered: boolean;
            /** Status Code */
            status_code?: number | null;
            /** Error */
            error?: string | null;
        };
        /** ExportBatchResponse */
        ExportBatchResponse: {
            /** Batch Id */
            batch_id: string;
            cause: components["schemas"]["CauseFamily"];
            /** Remedy Code */
            remedy_code: string;
            /** Wallet Ids */
            wallet_ids: string[];
            /** Cost Bdt */
            cost_bdt: number;
            /** Approved By */
            approved_by: string;
            /** Approved At */
            approved_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            store: components["schemas"]["StoreKind"];
            /**
             * Stub
             * @default false
             */
            stub: boolean;
            /** Model Version */
            model_version?: string | null;
        };
        /**
         * LockReason
         * @enum {string}
         */
        LockReason: "open" | "cooldown";
        /** LockedWallet */
        LockedWallet: {
            /** Wallet Id */
            wallet_id: string;
            reason: components["schemas"]["LockReason"];
            /** Until */
            until?: string | null;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            /** Access Token */
            access_token: string;
            /** User Id */
            user_id: string;
            role: components["schemas"]["UserRole"];
        };
        /**
         * PayCycle
         * @enum {string}
         */
        PayCycle: "weekly" | "biweekly" | "monthly";
        /** Receipt */
        Receipt: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Sent */
            sent: number;
            /** Delivered */
            delivered: number;
            /** Failed */
            failed: number;
            /** Gateway Ref */
            gateway_ref?: string | null;
            /** Failed Wallet Ids */
            failed_wallet_ids?: string[];
        };
        /** Remedy */
        Remedy: {
            /** Remedy Code */
            remedy_code: string;
            /** Label */
            label: string;
            /** Unit Cost Bdt */
            unit_cost_bdt: number;
        };
        /** RuleBaseline */
        RuleBaseline: {
            /** Fired */
            fired: boolean;
            /** Action */
            action: string;
        };
        /** ScoreRequest */
        ScoreRequest: {
            /** Wallets */
            wallets: components["schemas"]["WalletHistory"][];
        };
        /** ScoreResponse */
        ScoreResponse: {
            /** Model Version */
            model_version: string;
            /** Tau */
            tau: number;
            /** Delta */
            delta: number;
            /** Results */
            results: components["schemas"]["ScoreResult"][];
        };
        /** ScoreResult */
        ScoreResult: {
            /** Wallet Id */
            wallet_id: string;
            /** Weeks Silent */
            weeks_silent: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "attributed" | "refused";
            cause: components["schemas"]["CauseFamily"] | null;
            /** Posterior */
            posterior: {
                [key: string]: number;
            };
            /** Contributions */
            contributions: components["schemas"]["Contribution"][];
            /** Refusal Reasons */
            refusal_reasons: string[];
            rule_baseline: components["schemas"]["RuleBaseline"];
            remedy: components["schemas"]["Remedy"] | null;
        };
        /** SmsStatus */
        SmsStatus: {
            /** Gateway Connected */
            gateway_connected: boolean;
            /** Webhook */
            webhook?: ("delivered" | "failed") | null;
            /** Sent */
            sent?: number | null;
            /** Delivered */
            delivered?: number | null;
            /** Failed */
            failed?: number | null;
            /** Failed Wallet Ids */
            failed_wallet_ids?: string[];
        };
        /**
         * StoreKind
         * @enum {string}
         */
        StoreKind: "local" | "supabase";
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "analyst" | "approver";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WalletHistory */
        WalletHistory: {
            /** Wallet Id */
            wallet_id: string;
            /** Acquired Week */
            acquired_week: number;
            /** Fee Week */
            fee_week: number;
            pay_cycle: components["schemas"]["PayCycle"];
            /** Weeks */
            weeks: components["schemas"]["WeekRow"][];
        };
        /** WeekRow */
        WeekRow: {
            /** Week */
            week: number;
            /** Txn Count */
            txn_count: number;
            /** Amount Bdt */
            amount_bdt: number;
            /**
             * Cashin Count
             * @default 0
             */
            cashin_count: number;
            /**
             * Cashout Ok
             * @default 0
             */
            cashout_ok: number;
            /**
             * Cashout Fail
             * @default 0
             */
            cashout_fail: number;
            /** App Share */
            app_share?: number | null;
            /**
             * District Changed
             * @default false
             */
            district_changed: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_batches_api_batches_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["BatchStatus"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_batch_api_batches_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_batch_api_batches__id__approve_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_batch_api_batches__id__reject_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_batch_api_batches__id__export_get: {
        parameters: {
            query?: {
                format?: "json" | "csv";
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportBatchResponse"];
                    "text/csv": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redeliver_batch_api_batches__id__redeliver_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeliveryResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaign_receipt_api_campaign_receipts_post: {
        parameters: {
            query?: never;
            header: {
                "x-whyquiet-timestamp": string;
                "x-whyquiet-signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Receipt"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Receipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_locked_wallets_api_wallets_locked_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LockedWallet"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_audit_api_batches__id__audit_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_api_score_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
